import { Profile, Organization, OrganizationMember, Project, Task } from '../types/database';

export const DEMO_USER_ID = 'demo-user-10111213-1415-1617-1819-202122232425';

export const DEMO_PROFILE: Profile = {
  id: DEMO_USER_ID,
  full_name: 'Elena Rostova',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
};

export const DEMO_ORGANIZATION: Organization = {
  id: 'org-olive-prime-001',
  name: 'De-Olive Design & DBMS Labs',
  industry: 'Technology & Software',
  team_size: '6-20',
  created_by: DEMO_USER_ID,
  created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
};

export const DEMO_TEAM_MEMBERS: (OrganizationMember & { profile: Profile })[] = [
  {
    id: 'member-01',
    organization_id: 'org-olive-prime-001',
    user_id: DEMO_USER_ID,
    role: 'owner',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    profile: DEMO_PROFILE,
  },
  {
    id: 'member-02',
    organization_id: 'org-olive-prime-001',
    user_id: 'demo-user-02',
    role: 'admin',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    profile: {
      id: 'demo-user-02',
      full_name: 'Marcus Vance',
      avatar_url: null,
      created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
  },
  {
    id: 'member-03',
    organization_id: 'org-olive-prime-001',
    user_id: 'demo-user-03',
    role: 'member',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    profile: {
      id: 'demo-user-03',
      full_name: 'Chloe Sinclair',
      avatar_url: null,
      created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
  },
  {
    id: 'member-04',
    organization_id: 'org-olive-prime-001',
    user_id: 'demo-user-04',
    role: 'member',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    profile: {
      id: 'demo-user-04',
      full_name: 'Julian Thorne',
      avatar_url: null,
      created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
  },
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-01',
    organization_id: 'org-olive-prime-001',
    name: 'Apollo Cloud Infrastructure Migration',
    description: 'Transitioning multi-region database replication and failover architecture onto Supabase dedicated pools.',
    status: 'active',
    start_date: '2026-09-01',
    due_date: '2026-11-15',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    id: 'proj-02',
    organization_id: 'org-olive-prime-001',
    name: 'Enterprise RBAC & Security Audit',
    description: 'Enforcing Postgres Row Level Security policies across public schema and user privilege isolation.',
    status: 'active',
    start_date: '2026-09-15',
    due_date: '2026-10-30',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 'proj-03',
    organization_id: 'org-olive-prime-001',
    name: 'Client Portal Redesign v2.4',
    description: 'Unified client telemetry overview and project deliverable tracker with olive brand system.',
    status: 'planning',
    start_date: '2026-11-01',
    due_date: '2026-12-20',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'proj-04',
    organization_id: 'org-olive-prime-001',
    name: 'Legacy MySQL Dump & Schema Normalize',
    description: 'De-normalizing historical client activity records and automated script ingestion.',
    status: 'completed',
    start_date: '2026-08-01',
    due_date: '2026-09-10',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: 'task-01',
    organization_id: 'org-olive-prime-001',
    project_id: 'proj-01',
    title: 'Audit Postgres pg_stat_activity connection limits',
    description: 'Analyze connection pooling spikes and verify pgbouncer transaction configuration.',
    status: 'in_progress',
    priority: 'high',
    assignee_id: DEMO_USER_ID,
    due_date: '2026-10-12',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'task-02',
    organization_id: 'org-olive-prime-001',
    project_id: 'proj-01',
    title: 'Benchmarking read-replica latencies under load',
    description: 'Execute automated stress script across EU and US edge clusters.',
    status: 'todo',
    priority: 'medium',
    assignee_id: 'demo-user-02',
    due_date: '2026-10-22',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'task-03',
    organization_id: 'org-olive-prime-001',
    project_id: 'proj-02',
    title: 'Verify organization_members tenant isolation RLS',
    description: 'Run automated permission injection tests to confirm no cross-tenant leaking.',
    status: 'in_progress',
    priority: 'high',
    assignee_id: 'demo-user-03',
    due_date: '2026-10-15',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'task-04',
    organization_id: 'org-olive-prime-001',
    project_id: 'proj-02',
    title: 'Draft Security & Compliance whitepaper summary',
    description: 'Document SOC2 type II adherence and schema column encryption policies.',
    status: 'done',
    priority: 'low',
    assignee_id: 'demo-user-04',
    due_date: '2026-10-05',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'task-05',
    organization_id: 'org-olive-prime-001',
    project_id: 'proj-03',
    title: 'Wireframe task progress bar & timeline components',
    description: 'Construct responsive desktop layout adhering to 1440px baseline.',
    status: 'todo',
    priority: 'medium',
    assignee_id: DEMO_USER_ID,
    due_date: '2026-11-04',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'task-06',
    organization_id: 'org-olive-prime-001',
    project_id: 'proj-04',
    title: 'Validate foreign keys on projects.organization_id',
    description: 'Verify referential integrity checks and cascade rules.',
    status: 'done',
    priority: 'high',
    assignee_id: 'demo-user-02',
    due_date: '2026-09-08',
    created_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
];

export const DEMO_INVITATIONS = [
  {
    id: 'invite-demo-01',
    organization_id: 'org-olive-prime-001',
    email: 'sarah.connor@cyberdyne.org',
    role: 'admin' as const,
    token: '7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d',
    status: 'pending' as const,
    invited_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    expires_at: new Date(Date.now() + 5 * 86400000).toISOString(),
  },
  {
    id: 'invite-demo-02',
    organization_id: 'org-olive-prime-001',
    email: 'alex.rivera@deolive.io',
    role: 'member' as const,
    token: '1f2e3d4c-5b6a-7f8e-9d0c-1b2a3f4e5d6c',
    status: 'pending' as const,
    invited_by: DEMO_USER_ID,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    expires_at: new Date(Date.now() + 6 * 86400000).toISOString(),
  },
];
